#ifndef VALUES_HPP
#define VALUES_HPP

#define MIN_X 0.0
#define MAX_X 1000.0
#define MIN_Y 0.0
#define MAX_Y 1000.0

#define COUNT_BASE_NPCS 50

#define KNIGHT_MOVE_DISTANCE 30.0
#define ELF_MOVE_DISTANCE 10.0
#define DRAGON_MOVE_DISTANCE 50.0

#define KNIGHT_ATTACK_RANGE 10.0
#define ELF_ATTACK_RANGE 50.0
#define DRAGON_ATTACK_RANGE 30.0

#endif
